# Generated by Django 4.1.8 on 2023-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_desc_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_tournament_team',
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('tournament', 'captain'), name='unique_tournament_team'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_tournament_team_name'),
        ),
    ]
