# Generated by Django 4.1.8 on 2023-05-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_team_unique_tournament_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Zugelassen'),
        ),
    ]
