# Generated by Django 4.1.8 on 2023-05-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_team_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['created_at'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
