# Generated by Django 4.1.8 on 2023-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_team_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='team',
            name='state',
            field=models.CharField(choices=[('E', 'Eingeschrieben'), ('A', 'Zugelassen'), ('R', 'Abgelehnt')], default='E', max_length=1, verbose_name='Status'),
        ),
    ]
