# Generated by Django 4.1.8 on 2023-05-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_remove_team_is_approved_team_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['created_at'], 'permissions': [('contact_team', 'Can contact team captain')], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
