# Generated by Django 4.1.8 on 2023-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Spieler'),
            preserve_default=False,
        ),
    ]
