# Generated by Django 4.1.8 on 2023-05-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournament_players'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='unique_team_player',
        ),
    ]
