# Generated by Django 4.2.1 on 2023-11-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_player_unique_team_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Ist sichtbar?'),
        ),
    ]
