# Generated by Django 4.1.8 on 2023-05-06 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Titel')),
                ('date', models.DateField(verbose_name='Datum')),
                ('desc', models.TextField(verbose_name='Beschreibung')),
                ('state', models.SmallIntegerField(choices=[(0, 'Vorbereitet'), (1, 'Geöffnet'), (2, 'Geschlossen'), (3, 'Archiviert')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Veranstaltung',
                'verbose_name_plural': 'Veranstaltungen',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Bemerkung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freiwilliger',
                'verbose_name_plural': 'Freiwillige',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='volunteer',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_volunteer'),
        ),
    ]
