# Generated by Django 4.1.8 on 2023-05-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['created_at'], 'permissions': [('contact_volunteer', 'Can contact volunteer')], 'verbose_name': 'Freiwilliger', 'verbose_name_plural': 'Freiwillige'},
        ),
    ]
