# Generated by Django 4.1.6 on 2023-02-07 16:21

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[accounts.validators.PhoneValidator()], verbose_name='mobile number'),
        ),
    ]
