# Generated by Django 4.1.8 on 2023-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_modification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Veränderung', 'verbose_name_plural': 'Veränderungen'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'Benutzer', 'verbose_name_plural': 'Benutzer'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-Mail-Adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mobilnummer'),
        ),
    ]
