# Generated by Django 4.2.8 on 2023-12-06 07:46

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_faculty_user_student_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='Die E-Mail-Adresse darf nur aus Buchstaben, Ziffern, Bindestrichen oder Punkten bestehen und muss mit "@st.ovgu.de" oder "@stud.h2.de" enden.', regex='^[^\\s]+@(st\\.ovgu\\.de|stud\\.h2\\.de)$')], verbose_name='E-Mail-Adresse'),
        ),
    ]
