# Generated by Django 4.1.6 on 2023-02-10 07:25

from django.db import migrations, models
import field_trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=field_trips.models.image_path),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
