# Generated by Django 4.1.8 on 2023-05-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_alter_excursion_options_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Bemerkung'),
        ),
    ]
