# Generated by Django 4.1.8 on 2023-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0004_participant_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Eingeschrieben'), (1, 'Zugelassen'), (2, 'Abgelehnt')], default=0, verbose_name='Status'),
        ),
    ]
