# Generated by Django 4.1.8 on 2023-05-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0006_excursion_ask_for_car_participant_is_driver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['created_at'], 'permissions': [('contact_participant', 'Can contact participant')], 'verbose_name': 'Teilnehmer', 'verbose_name_plural': 'Teilnehmer'},
        ),
    ]
