# Generated by Django 4.2.20 on 2025-11-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0007_alter_participant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='anticipated_degree',
            field=models.TextField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master')], null=True, verbose_name='Voraussichtlicher Abschluss'),
        ),
    ]
