# Generated by Django 4.1.8 on 2023-05-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_alter_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stocked',
            field=models.BooleanField(default=False, verbose_name='Auf Lager'),
        ),
    ]
