# Generated by Django 4.1.8 on 2023-05-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0007_alter_order_size_remove_order_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ausstehend'), (1, 'Bestätigt'), (2, 'Bezahlt'), (3, 'Abholbereit'), (4, 'Abgeschlossen'), (5, 'Storniert')], default=0, verbose_name='Status'),
        ),
    ]
