# Generated by Django 4.2.1 on 2023-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0008_alter_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_stocked',
        ),
        migrations.AddField(
            model_name='size',
            name='is_stocked',
            field=models.BooleanField(default=False, verbose_name='Auf Lager'),
        ),
    ]
