# Generated by Django 4.2.1 on 2023-06-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0009_remove_product_is_stocked_size_is_stocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['product', 'position'], 'verbose_name': 'Größe', 'verbose_name_plural': 'Größen'},
        ),
        migrations.AddField(
            model_name='size',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddConstraint(
            model_name='size',
            constraint=models.UniqueConstraint(fields=('product', 'position'), name='unique_position'),
        ),
    ]
